---
title: 'Etapa 2: Comprensión y preparación de datos'
author:
  - Mariana Hernández Jiménez   |   A00841920
  - Andrea Estefanía De la Peña Contreras  |  A00840973
  - Carolina Navarro Barrón   |   A00839486
  - Annette Abigail Choque Millán   |  A00842260
  - Maricarmen Terán Maturino   |   A00841435
date: "2025-10-09"
output:
  pdf_document: default
  word_document: default
fontsize: 10pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(kableExtra)
```

## Preparación de los datos

```{r, echo = FALSE, include = FALSE}
M19 = read.csv("Datos_molec_2019-1.csv")
M20 = read.csv("Datos_molec_2020-1.csv")
M21 = read.csv("Datos_molec_2021-1.csv")
M22 = read.csv("Datos_molec_2022-1.csv")
M23 = read.csv("Datos_molec_2023-1.csv")
M24 = read.csv("Datos_molec_2024-1.csv")

#Dimensión de cada base de datos (anual):
dim(M19)
dim(M20)
dim(M21)
dim(M22)
dim(M23)
dim(M24)

names(M24) #muestra la lista de nombres de las variables
View(M22) #se mostrará una hoja electrónica aparte con los datos
View(M23)
View(M24)

#108 variables en todas las bases de datos, con registros que rondan entre 1948 y 2016 anuales.
```

```{r, echo = FALSE, include = FALSE}
#dataframe con las variables, incluyendo su nombre, tipo (categórico/Numérico) y valores posibles que puede tomar
D19 = read.csv("Diccionario_molec_2019-1.csv")
D20 = read.csv("Diccionario_molec_2020-1.csv")
D21 = read.csv("Diccionario_molec_2021-1.csv")
D22 = read.csv("Diccionario_molec_2022-1.csv")
D23 = read.csv("Diccionario_molec_2023-1.csv")
D24 = read.csv("Diccionario_molec_2024-1.csv")

df_caracteristicas_variable = D24%>%select("NOMBRE_CAMPO", "TIPO", "NEMONICO","RANGO_CLAVES")
View(df_caracteristicas_variable)
```

### Variables de interés

```{r}
tabla <- data.frame(
  Nombre = c(
    "nivel",
    "cond_activ",
    "sexo",
    "edad",
    "p7_3",
    "p4",
    "p5"
  ),
  Tipo = c(
    "Categórica",
    "Categórica",
    "Categórica",
    "Cuantitativa",
    "Cuantitativa",
    "Cuantitativa",
    "Categórica"
  ),
  Valores = c(
    # nivel
    "00 = Ninguno \n
01 = Preescolar \n
02 = Primaria \n
03 = Secundaria \n
04 = Preparatoria o bachillerato \n
05 = Normal básica \n
06 = Carrera técnica \n
07 = Profesional \n
08 = Maestría \n
09 = Doctorado \n
99 = No sabe \n
b = Blanco por pase",
    # cond_activ
    "01 = trabajó para obtener ingresos \n
02 = trabajó sin pago ayudando en el negocio o actividad que desempeña un familiar \n
03 = no trabajó, pero sí tenía trabajo \n
04 = buscó trabajo \n
05 = está en espera de que le resuelvan una solicitud de un trabajo al que acudió \n
06 = es estudiante \n
07 = se dedica a los quehaceres de su hogar \n
08 = es jubilado(a) o pensionado(a) \n
09 = está incapacitado(a) permanentemente para trabajar \n
10 = Otra situación \n
99 = No especificado",
    # sexo
    "1 = Hombre \n
2 = Mujer",
    # edad
    "18 - 98",
    # p7_3
    "b = Blanco por pase \n
000030 - 015000 (pesos) \n
999999 = No sabe",
    # p4
    "01 - 70 = Libros \n
b = Blanco por pase",
    # p5
    "1 = Por trabajo \n
2 = Por estudio \n
3 = Por cultura general o por estar al día \n
4 = Por gusto o por entretenimiento \n
5 = Por religión \n
6 = Otro \n
b = Blanco por pase"
  )
)

kable(tabla, escape = FALSE,
      col.names = c("Nombre","Tipo","Valores que puede tomar")) %>%
  kable_styling(full_width = TRUE, bootstrap_options = c("striped","hover"))

```


## Seleccion del conjunto de datos a utilizar y los años 
```{r, echo = FALSE, include = FALSE}

#Años seleccionados: 2022, 2023, 2024
#Variables seleccionadas: nivel, cond_activ, sexo, edad, p7_3, p4, p5

M22final = M22[, c("nivel", "cond_act", "sexo", "edad", "p7_3", "p4", "p5")]
M23final = M23[, c("nivel", "cond_act", "sexo", "edad", "p7_3", "p4", "p5")]
M24final = M24[, c("nivel", "cond_act", "sexo", "edad", "p7_3", "p4", "p5")]

MA22final=na.omit(M22final)
MA23final=na.omit(M23final)
MA24final=na.omit(M24final)

#dataframe con las variables seleccionadas, incluyendo su nombre, descripción, tipo (categórico/Numérico) y valores posibles que puede tomar

variables_seleccionadas = c("nivel","cond_act","sexo","edad","P7_3", "p4", "p5" )
df_caracteristicas_variable_seleccionadas <- df_caracteristicas_variable[df_caracteristicas_variable[,3] %in% variables_seleccionadas, ]
View(df_caracteristicas_variable_seleccionadas)
```

## Analisis de Datos cuantitativos para 2022, 2023 y 2024
```{r}

analisis_cuant = function(x){
  x = as.numeric(x)
  x = x[!is.na(x)]
  
  if(length(x) < 2){
    return(data.frame(
      Media = NA, Mediana = NA, Rango_Medio = NA, Desviacion = NA,
      Coef_Variacion = NA, Q1 = NA, Q2 = NA, Q3 = NA,
      Sesgo = NA, Curtosis = NA
    ))
  }
  
  media = mean(x)
  mediana = median(x)
  rango_medio = (max(x) + min(x)) / 2
  desv = sd(x)
  coef_var = ifelse(media != 0, (desv / media) * 100, NA)
  cuartiles = quantile(x, probs = c(0.25, 0.5, 0.75))
  
  # Sesgo y curtosis
  
  if (desv > 0){
    sesgo = sum((x - media)^3) / (length(x) * desv^3)
    curtosis = sum((x - media)^4) / (length(x) * desv^4)
  } else {
    sesgo = NA
    curtosis = NA
  }
  
  data.frame(
    Media = round(media, 2),
    Mediana = round(mediana, 2),
    Rango_Medio = round(rango_medio, 2),
    Desviacion = round(desv, 2),
    Coef_Variacion = round(coef_var, 2),
    Q1 = round(cuartiles[1], 2),
    Q2 = round(cuartiles[2], 2),
    Q3 = round(cuartiles[3], 2),
    Sesgo = round(sesgo, 2),
    Curtosis = round(curtosis, 2)
  )
}

# 2022
Datos22 = MA22final[, c("edad", "p7_3", "p4")]
tabla_cuant22 = lapply(Datos22, analisis_cuant)
tabla_cuant22 = do.call(rbind, tabla_cuant22)
rownames(tabla_cuant22) = paste0(names(Datos22), "_2022")

# 2023
Datos23 <- MA23final[, c("edad", "p7_3", "p4")]
tabla_cuant23 = lapply(Datos23, analisis_cuant)
tabla_cuant23 = do.call(rbind, tabla_cuant23)
rownames(tabla_cuant23) = paste0(names(Datos23), "_2023")

# 2024
Datos24 = MA24final[, c("edad", "p7_3", "p4")]
tabla_cuant24 = lapply(Datos24, analisis_cuant)
tabla_cuant24 = do.call(rbind, tabla_cuant24)
rownames(tabla_cuant24) = paste0(names(Datos24), "_2024")

tabla_cuant_todos = rbind(tabla_cuant22, tabla_cuant23, tabla_cuant24)

kable(tabla_cuant_todos, caption = "Medidas descriptivas de las variables cuantitativas por año") %>%
  kable_styling(full_width = TRUE, bootstrap_options = c("striped","hover"))


```




## Visualización de variables cuantitativas
```{r}
# 2022
Datos_cuant22 = MA22final[, c("edad", "p7_3", "p4")]

par(mfrow = c(1,3))
boxplot(Datos_cuant22, main = "Boxplots 2022", col = "blue", las = 2)
par(mfrow = c(1,1))

for (v in names(Datos_cuant22)) {
  hist(Datos_cuant22[[v]], 
       main = paste("Histograma de", v, "2022"), 
       xlab = v, col = "green", border = "black")
}

correlacion22 = cor(Datos_cuant22, use = "complete.obs")
kable(round(correlacion22, 2), caption = "Matriz de correlaciones (2022)") %>%
  kable_styling(full_width = TRUE, bootstrap_options = c("striped","hover"))


# 2023
Datos_cuant23 = MA23final[, c("edad", "p7_3", "p4")]

par(mfrow = c(1,3))
boxplot(Datos_cuant23, main = "Boxplots 2023", col = "red", las = 2)
par(mfrow = c(1,1))

for (v in names(Datos_cuant23)) {
  hist(Datos_cuant23[[v]], 
       main = paste("Histograma de", v, "2023"), 
       xlab = v, col = "pink", border = "black")
}

correlacion23 = cor(Datos_cuant23, use = "complete.obs")
kable(round(correlacion23, 2), caption = "Matriz de correlaciones (2023)") %>%
  kable_styling(full_width = TRUE, bootstrap_options = c("striped","hover"))


# 2024
Datos_cuant24 = MA24final[, c("edad", "p7_3", "p4")]

par(mfrow = c(1,3))
boxplot(Datos_cuant24, main = "Boxplots 2024", col = "yellow", las = 2)
par(mfrow = c(1,1))

for (v in names(Datos_cuant24)) {
  hist(Datos_cuant24[[v]], 
       main = paste("Histograma de", v, "2024"), 
       xlab = v, col = "orange", border = "black")
}

correlacion24 = cor(Datos_cuant24, use = "complete.obs")
kable(round(correlacion24, 2), caption = "Matriz de correlaciones (2024)") %>%
  kable_styling(full_width = TRUE, bootstrap_options = c("striped","hover"))


```

